// A directory of ZIP codes in Monterey County
export const zipCodeData: { [key: string]: { city: string; state: string } } = {
  "93901": { city: "Salinas", state: "CA" },
  "93902": { city: "Salinas", state: "CA" },
  "93905": { city: "Salinas", state: "CA" },
  "93906": { city: "Salinas", state: "CA" },
  "93907": { city: "Salinas", state: "CA" },
  "93908": { city: "Salinas", state: "CA" },
  "93920": { city: "Big Sur", state: "CA" },
  "93921": { city: "Carmel", state: "CA" },
  "93922": { city: "Carmel", state: "CA" },
  "93923": { city: "Carmel", state: "CA" },
  "93924": { city: "Carmel Valley", state: "CA" },
  "93925": { city: "Chualar", state: "CA" },
  "93926": { city: "Gonzales", state: "CA" },
  "93927": { city: "Greenfield", state: "CA" },
  "93928": { city: "Jolon", state: "CA" },
  "93930": { city: "King City", state: "CA" },
  "93932": { city: "Lockwood", state: "CA" },
  "93933": { city: "Marina", state: "CA" },
  "93940": { city: "Monterey", state: "CA" },
  "93942": { city: "Monterey", state: "CA" },
  "93943": { city: "Monterey", state: "CA" },
  "93944": { city: "Monterey", state: "CA" },
  "93950": { city: "Pacific Grove", state: "CA" },
  "93953": { city: "Pebble Beach", state: "CA" },
  "93954": { city: "San Ardo", state: "CA" },
  "93955": { city: "Seaside", state: "CA" },
  "93960": { city: "Soledad", state: "CA" },
  "95012": { city: "Castroville", state: "CA" },
  "95039": { city: "Moss Landing", state: "CA" },
};